### PR TITLE
Bugfix: fix closing of UDP routine

### LINKED ISSUE #112: utils.go udpDataCh: panic: send on closed channel
Hi 👋,

I just encountered this error.

```
panic: send on closed channel

goroutine 405 [running]:
github.com/netsampler/goflow2/utils.UDPStoppableRoutine.func1()
	go/pkg/mod/github.com/netsampler/goflow2@v1.1.0/utils/utils.go:171 +0x9a
created by github.com/netsampler/goflow2/utils.UDPStoppableRoutine
	go/pkg/mod/github.com/netsampler/goflow2@v1.1.0/utils/utils.go:164 +0x952
```

It seems that `udpDataCh` might be closed here https://github.com/netsampler/goflow2/blob/main/utils/utils.go#L184

But data will still be pushed to it from here https://github.com/netsampler/goflow2/blob/main/utils/utils.go#L171

### PR DESCRIPTION
**Pull request by lspgn**
Tentative to use only two channels and use the defer close.
Alternative to #117. Fixes #112 

cc @mariomac @AlexandreYang

### CODE REVIEW

File: utils/utils.go [hunk 1]
```diff
@@ -158,36 +158,41 @@ func UDPStoppableRoutine(stopCh <-chan struct{}, name string, decodeFunc decoder
...
+			if u.size == 0 { // Ignore 0 byte packets.
+				continue
+			}
+			u.payload = make([]byte, u.size)
+			copy(u.payload, payload[0:u.size])
+			select {
+			case <-stopCh:
 				return
+			default:
+				udpDataCh <- u
```
Comment (AlexandreYang) [inline utils/utils.go:180]: Could `udpDataCh <- u` here block forever if:
1/ line 179: enter `default:` case, but not reaching `udpDataCh <- u` yet
2/ line 189:  enter `case <-stopCh:` and `return`
3/ line 180: reached with `udpDataCh <- u` blocking since `udpDataCh` won't be consumed anymore at line 187

?

Comment (lspgn) [reply utils/utils.go:180]: Good catch. Added a drain.
```
	for _ = range udpDataCh {
		// drain
	}
```

**Comment by lspgn** [comment]
Also wondering if
```
	udpDataCh := make(chan udpData)
```
should be customizeable.
Otherwise it seems quite synchronous and could do:
```
select {
			case <-stopCh:
				return
			default:
				process(u.size, u.payload, u.pktAddr, processor, localIP, addrUDP, name)
			}
```

**Comment by AlexandreYang** [comment]
Indeed. The synchronous way might be enough.

About making `udpDataCh := make(chan udpData)`, I'm not sure if it will help with performance or smooth out bursts. Some benchmark/testing might be needed.
We already have customisable workers later in the pipeline, and `process(u.size, u.payload, u.pktAddr, processor, localIP, addrUDP, name)` seems to not do much itself:

```
// Send a message to be decoded to the pool.
func (p Processor) ProcessMessage(msg Message) {
	sendChannel := <-p.workerpool
	sendChannel <- msg
}
```

**Comment by AlexandreYang** [comment]
@lspgn Thanks a lot for this. Do you think releasing a new version soonish is possible?

(We are using goflow2 in [datadog-agent](https://github.com/DataDog/datadog-agent/) and the panic can impact other things abruptly during shutdown workflow.)

**Comment by lspgn** [comment]
Unsure when I'll release one.

But inside `go.mod` you should be able to use:
```
require github.com/netsampler/goflow2 v1.1.1-0.20220825033856-d6caeaacddbb
```

**Comment by AlexandreYang** [comment]
Thanks 👍
